language: r
cache: packages

addons:
  apt:
    packages:
      - libprotobuf-dev
      - libprotoc-dev
      - protobuf-compiler

after_success:
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
